### ISSUE TITLE
Updating dependencies

### ISSUE THREAD

**Issue by dbrgn** [mvirkkunen/stm32f103xx-usb#2]
There are some new dependencies:

- stm32f103xx 0.11
- stm32f103xx-hal
- cortex-m-rt 0.6

Would be great if you could update those, then I can give the crate a try. (My application is already on stm32f103xx 0.11 and the newer hal implementation.)

**Comment by mvirkkunen** [comment]
I actually just started upgrading to the 2018 edition, and I'll update the dependencies while I'm at it. Just a moment!

**Comment by mvirkkunen** [comment]
And it's done!

**Comment by dbrgn** [comment]
Thanks!
