### ISSUE TITLE
HID example

### ISSUE THREAD

**Issue by kfazz** [mvirkkunen/stm32f103xx-usb#3]
Any chance you could throw together a minimal HID example?
Also, how can the custom example be toggled from the host?
Thanks.

**Comment by mvirkkunen** [comment]
After I get usb-device itself published as a crate I'm planning on publishing at least two USB class crates, one for HID and one for serial. In the meantime if you want to see how you could talk to a custom USB device, you could check out the TestClass class I just added to usb-device, and the host program that connects and talks to it using libusb:

https://github.com/mvirkkunen/usb-device/tree/master/examples/test_class_host
https://github.com/mvirkkunen/usb-device/blob/master/src/test_class.rs

**Comment by robinkrahl** [comment]
@kfazz I implemented a simple HID class here: [hid.rs](https://git.ireas.org/ntw/tree/src/hid.rs).  It only uses the Set_Report and Get_Report requests, but it might be a good starting point for something more complicated.

**Comment by jmgao** [comment]
I implemented enough of HID to pretend to be a PS4 controller to Windows/Linux/PS4 [here](https://github.com/jmgao/passinglink/blob/master/src/hid/mod.rs)

The API needs work (the class and actual implementation are fairly coupled right now), and it's missing most of the difficult part of implementing a generic HID device, as the report descriptor is just a hard-coded byte array literal and reports are assembled by manual bit twiddling. At some point, I'll try to implement a keyboard with it to see if it's actually usable for more than my specific use case, and publish a crate.

(Side note: the [128 byte control transfer limit](https://github.com/mvirkkunen/usb-device/blob/12ee18c471501903f89dce82a38f36a855d94c00/src/control_pipe.rs#L25) is probably a problem: HID report descriptors can be comically large. The specific controller I'm emulating has a 160-byte long one.)

**Comment by mvirkkunen** [comment]
@jmgao Yes, the fixed size buffer is a problem. The plan is to make that configurable. Additionally a nice RAM saving measure could be to allow one to respond to a control transfer with a `'static [u8]` which is what descriptors usually are.
